export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RECEIVE_ACCOUNT_PRODUCT = 'RECEIVE_ACCOUNT_PRODUCT';
export const RECEIVE_ACCOUNT_BALANCES = 'RECEIVE_ACCOUNT_BALANCE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
